const URL="https://buappkzwllmfyevvdmfi.supabase.co",KEY="sb_publishable_a0MvZqJwZAbd5FyruLEH7A_QQBcXYY1",sb=window.supabase.createClient(URL,KEY);
let user=null,profile=null,week=null,teams=[],selected=new Set(),cap=null,mode="login";
const $=id=>document.getElementById(id), esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;"), initials=n=>String(n||"?").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),2800)}
async function loadWeek(){let r=await sb.from("weeks").select("*").eq("is_current",true).maybeSingle();if(r.error)return toast("Could not load the current week.");week=r.data;if(!week)return; $("weekNumber").textContent="Week "+week.week_number;$("weekTitle").textContent=week.title||"Cove Cricket Fantasy";$("leaderboardWeek").textContent="Week "+week.week_number;$("weekStatus").textContent=week.selections_open?"Selections are open":"Selections are locked";$("weekDot").classList.toggle("locked",!week.selections_open)}
async function loadTeams(){teams=[];if(!week)return render();let r=await sb.from("week_teams").select("id,team_id,playing,captain_player_id,club_teams(id,name,sort_order)").eq("week_id",week.id).order("team_id");if(r.error)return render();for(const x of r.data||[]){let p=await sb.from("week_players").select("player_id,players(id,full_name)").eq("week_team_id",x.id);let ps=(p.data||[]).map(y=>({id:y.player_id,name:y.players?.full_name||"Unnamed player"}));let cn=ps.find(y=>y.id===x.captain_player_id)?.name||"Captain";teams.push({weekTeamId:x.id,id:x.team_id,name:x.club_teams?.name||"Team",sort:x.club_teams?.sort_order||99,playing:!!x.playing,captainId:x.captain_player_id,captainName:cn,players:ps})}teams.sort((a,b)=>a.sort-b.sort);render();renderPlayers();if(profile?.is_admin)initEditor()}
function count(t){return t.players.filter(p=>selected.has(p.id)).length}
function render(){let html="";for(const t of teams){html+=`<div class="team-card"><div class="team-head"><b>${esc(t.name)}</b><span class="state ${t.playing?"playing":""}">${t.playing?"SELECT 2":"NOT PLAYING"}</span></div>`;if(!t.playing)html+=`<div class="off">This team is not playing this gameweek.</div>`;else if(!t.players.length)html+=`<div class="off">The 11-player squad has not been configured yet.</div>`;else for(const p of t.players){let s=selected.has(p.id);html+=`<div class="player-row ${s?"selected":""}"><div class="avatar">${initials(p.name)}</div><div class="player-main"><div class="player-name">${esc(p.name)}</div><div class="sub">${esc(t.name)}</div></div><button class="select ${s?"selected":""}" data-player="${p.id}" data-team="${t.id}" ${week?.selections_open?"":"disabled"}>${s?"Selected":"Select"}</button></div>`}html+="</div>"}$("teams").innerHTML=html||`<div class="empty">This week has not been configured yet.</div>`;$("teams").querySelectorAll("[data-player]").forEach(b=>b.onclick=()=>toggle(teams.find(t=>String(t.id)===b.dataset.team),b.dataset.player));
$("captains").innerHTML=teams.filter(t=>t.playing&&t.captainId).map(t=>`<button class="captain ${cap===t.captainId?"selected":""}" data-cap="${t.captainId}"><div class="cap">C</div><b>${esc(t.captainName)}</b><div class="sub">${esc(t.name)}</div></button>`).join("")||`<div class="empty">Playing-team captains will appear here.</div>`;$("captains").querySelectorAll("[data-cap]").forEach(b=>b.onclick=()=>{cap=cap===b.dataset.cap?null:b.dataset.cap;render()});
let expected=teams.filter(t=>t.playing).length*2;$("counter").textContent=`${selected.size} / ${expected}`;$("selectedText").textContent=`${selected.size} player${selected.size===1?"":"s"} selected`;let ct=teams.find(t=>String(t.captainId)===String(cap));$("captainText").textContent=ct?`Fantasy Captain: ${ct.captainName}`:"Fantasy Captain: not chosen";$("loginNotice").classList.toggle("hidden",!!user)}
function toggle(t,id){if(!week?.selections_open)return toast("Selections are locked.");if(selected.has(id))selected.delete(id);else{if(count(t)>=2)return toast(`You can only select 2 players from ${t.name}.`);selected.add(id)}render()}
async function loadSaved(){if(!user||!week)return;let r=await sb.from("fantasy_teams").select("id,captain_player_id").eq("user_id",user.id).eq("week_id",week.id).maybeSingle();selected.clear();cap=r.data?.captain_player_id||null;if(r.data){let x=await sb.from("fantasy_team_players").select("player_id").eq("fantasy_team_id",r.data.id);for(const p of x.data||[])selected.add(p.player_id)}render()}
async function saveTeam(){if(!user)return openAuth("login");if(!week?.selections_open)return toast("Selections are locked.");for(const t of teams.filter(x=>x.playing))if(count(t)!==2)return toast(`Select exactly 2 players from ${t.name}.`);let ct=teams.find(t=>String(t.captainId)===String(cap));if(!ct||!ct.playing)return toast("Choose a captain from a playing team.");let r=await sb.from("fantasy_teams").select("id").eq("user_id",user.id).eq("week_id",week.id).maybeSingle();if(r.error)return toast(r.error.message);let id=r.data?.id;if(id){let u=await sb.from("fantasy_teams").update({captain_player_id:cap}).eq("id",id);if(u.error)return toast(u.error.message);await sb.from("fantasy_team_players").delete().eq("fantasy_team_id",id)}else{let i=await sb.from("fantasy_teams").insert({user_id:user.id,week_id:week.id,captain_player_id:cap}).select("id").single();if(i.error)return toast(i.error.message);id=i.data.id}let ins=await sb.from("fantasy_team_players").insert([...selected].map(player_id=>({fantasy_team_id:id,player_id})));if(ins.error)return toast(ins.error.message);toast("Team saved successfully.")}
function renderPlayers(){let all=[];for(const t of teams)for(const p of t.players)if(!all.some(x=>x.id===p.id))all.push({id:p.id,name:p.name,team:t.name});$("playersGrid").innerHTML=all.length?all.map(p=>`<div class="player-card"><div class="avatar">${initials(p.name)}</div><h3>${esc(p.name)}</h3><p>${esc(p.team)}</p></div>`).join(""):`<div class="empty">Players will appear here once squads are configured.</div>`}
function openAuth(m){mode=m;$("authModal").classList.remove("hidden");$("authTitle").textContent=m==="login"?"Sign in":"Create an account";$("authSubtitle").textContent=m==="login"?"Sign in to save your fantasy team.":"Create an account to save your fantasy team.";$("authPrimary").textContent=m==="login"?"Sign in":"Create account";$("authSwitch").textContent=m==="login"?"Create account":"I already have an account";$("authMessage").textContent=""}
function closeAuth(){$("authModal").classList.add("hidden")}
async function auth(){let email=$("email").value.trim(),password=$("password").value;if(!email||password.length<6)return $("authMessage").textContent="Enter an email and a password of at least 6 characters.";$("authMessage").textContent="Working…";let r=mode==="login"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});if(r.error)return $("authMessage").textContent=r.error.message;if(mode==="signup"&&!r.data.session)return $("authMessage").textContent="Account created. You can now sign in.";closeAuth();toast(mode==="login"?"Signed in.":"Account created.");await refresh()}
async function refresh(){let r=await sb.auth.getUser();user=r.data.user||null;profile=null;if(user){let p=await sb.from("profiles").select("username,display_name,is_admin").eq("id",user.id).maybeSingle();profile=p.data||null}$("editorNav").classList.toggle("hidden",!profile?.is_admin);$("editor").classList.toggle("hidden",!profile?.is_admin);$("accountBtn").textContent=user?(profile?.display_name||"Account"):"Sign in";if(user)await loadSaved();render();if(profile?.is_admin)initEditor()}
function initEditor(){if(!week||!profile?.is_admin)return;$("editTitle").value=week.title||"";$("editNumber").value=week.week_number;$("editOpen").checked=!!week.selections_open;$("editorTeams").innerHTML=teams.map(t=>`<div class="editor-team"><label><input type="checkbox" data-et="${t.id}" ${t.playing?"checked":""}>${esc(t.name)}</label><span>${t.players.length}/11</span></div>`).join("")}
$("saveBtn").onclick=saveTeam;$("accountBtn").onclick=()=>user?$("logoutModal").classList.remove("hidden"):openAuth("login");$("closeAuth").onclick=closeAuth;$("authPrimary").onclick=auth;$("authSwitch").onclick=()=>openAuth(mode==="login"?"signup":"login");$("logoutNo").onclick=()=>$("logoutModal").classList.add("hidden");$("logoutYes").onclick=async()=>{await sb.auth.signOut();$("logoutModal").classList.add("hidden");user=null;profile=null;selected.clear();cap=null;render();toast("Signed out.")};
$("saveWeek").onclick=async()=>{if(!profile?.is_admin)return;let r=await sb.from("weeks").update({title:$("editTitle").value.trim(),week_number:Math.max(1,Number($("editNumber").value)||1),selections_open:$("editOpen").checked}).eq("id",week.id);if(r.error)toast(r.error.message);else{toast("Week settings saved.");await loadWeek()}};
$("saveTeams").onclick=async()=>{if(!profile?.is_admin)return;for(const t of teams){let el=document.querySelector(`[data-et="${t.id}"]`);let r=await sb.from("week_teams").update({playing:!!el?.checked}).eq("id",t.weekTeamId);if(r.error)return toast(r.error.message)}toast("Playing teams saved.");await loadTeams()};
sb.auth.onAuthStateChange(()=>setTimeout(refresh,0));
(async()=>{await loadWeek();await loadTeams();await refresh()})();